package View;

import javax.swing.*;
import java.awt.*;

/**
 * This class represents the main menu panel of the game
 * It is a gateway to all the other panels/forms
 */
public class MainMenu {
    private static MainMenu self;

    private static final String NAME = "mainMenu";

    private JPanel menuPanel;
    private JLabel titleLabel;
    private JButton newGameButton;
    private JButton customGameButton;
    private JButton loadGameButton;
    private JButton instructionsButton;

    /**
     * Private constructor to ensure singleton integrity.
     */
    private MainMenu() {
    }

    /**
     * Gets singleton instance of this class
     */
    public static MainMenu getInstance() {
        if (self == null) {
            self = new MainMenu();
        }
        return self;
    }

    /**
     * Gets the name of this panel.
     */
    public static String getName() {
        return NAME;
    }

    /**
     * @return the main menu panel
     */
    public JPanel getPanel() {
        return menuPanel;
    }

    /**
     * @return the new game button
     */
    public JButton getNewGameButton() {
        return newGameButton;
    }

    /**
     * @return the custom game button
     */
    public JButton getCustomGameButton() {
        return customGameButton;
    }

    /**
     * @return the load game button
     */
    public JButton getLoadGameButton() {
        return loadGameButton;
    }

    /**
     * @return the instructions button
     */
    public JButton getInstructionsButton() {
        return instructionsButton;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        menuPanel = new JPanel();
        menuPanel.setLayout(new GridBagLayout());
        titleLabel = new JLabel();
        Font titleLabelFont = this.$$$getFont$$$(null, Font.BOLD, 36, titleLabel.getFont());
        if (titleLabelFont != null) titleLabel.setFont(titleLabelFont);
        titleLabel.setName("titleLabel");
        titleLabel.setText("Toguz Korgool");
        titleLabel.setVerticalAlignment(0);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.ipady = 50;
        gbc.insets = new Insets(0, 60, 0, 60);
        menuPanel.add(titleLabel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menuPanel.add(spacer1, gbc);
        newGameButton = new JButton();
        newGameButton.setName("newGameButton");
        newGameButton.setText("New Game");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.ipadx = 55;
        gbc.ipady = 10;
        gbc.insets = new Insets(15, 0, 15, 0);
        menuPanel.add(newGameButton, gbc);
        customGameButton = new JButton();
        customGameButton.setName("customGameButton");
        customGameButton.setText("Custom Game");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.ipadx = 40;
        gbc.ipady = 10;
        gbc.insets = new Insets(15, 0, 15, 0);
        menuPanel.add(customGameButton, gbc);
        loadGameButton = new JButton();
        loadGameButton.setName("loadGameButton");
        loadGameButton.setText("Load Game");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.ipadx = 58;
        gbc.ipady = 10;
        gbc.insets = new Insets(15, 0, 15, 0);
        menuPanel.add(loadGameButton, gbc);
        instructionsButton = new JButton();
        instructionsButton.setName("instructionsButton");
        instructionsButton.setText("Instructions");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.ipadx = 60;
        gbc.ipady = 10;
        gbc.insets = new Insets(15, 0, 25, 0);
        menuPanel.add(instructionsButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return menuPanel;
    }
}
